spring:
  data:
    redis:
      database: 10
      port: 6379
      host: localhost
      password: 123456
  mail:
    host: smtp.qq.com
    username: 925192866@qq.com
    password: vbuqkchnaxuabccj
    port: 587
    default-encoding: UTF-8
